FROM golang:1-alpine as builder
RUN apk --no-cache add gcc musl-dev linux-headers cmake make clang build-base clang-static clang-dev

# Build the mock builder executable.
ADD . /source
WORKDIR /source
RUN go build -o mockbuilder ./builder/mock/cmd/

# Build the mock builder run container.
FROM alpine:latest
ADD . /source
WORKDIR /source
COPY --from=builder /source/mockbuilder .

ENTRYPOINT ["./mockbuilder"]